@startuml packages_KMS_System
set namespaceSeparator none
package "chatbot-be" as chatbot-be {
}
package "chatbot-be.config" as chatbot-be.config {
}
package "chatbot-be.conftest" as chatbot-be.conftest {
}
package "chatbot-be.controller" as chatbot-be.controller {
}
package "chatbot-be.controller.authController" as chatbot-be.controller.authController {
}
package "chatbot-be.controller.chatbotController" as chatbot-be.controller.chatbotController {
}
package "chatbot-be.controller.kpiGroupController" as chatbot-be.controller.kpiGroupController {
}
package "chatbot-be.controller.kpiMasterController" as chatbot-be.controller.kpiMasterController {
}
package "chatbot-be.controller.kpiTrackerController" as chatbot-be.controller.kpiTrackerController {
}
package "chatbot-be.controller.schedulerController" as chatbot-be.controller.schedulerController {
}
package "chatbot-be.controller.userController" as chatbot-be.controller.userController {
}
package "chatbot-be.databaseConfig" as chatbot-be.databaseConfig {
}
package "chatbot-be.main" as chatbot-be.main {
}
package "chatbot-be.middleware" as chatbot-be.middleware {
}
package "chatbot-be.middleware.jwtMiddleware" as chatbot-be.middleware.jwtMiddleware {
}
package "chatbot-be.model" as chatbot-be.model {
}
package "chatbot-be.model.Base" as chatbot-be.model.Base {
}
package "chatbot-be.model.Chatbot" as chatbot-be.model.Chatbot {
}
package "chatbot-be.model.IngestionLog" as chatbot-be.model.IngestionLog {
}
package "chatbot-be.model.KPIGroup" as chatbot-be.model.KPIGroup {
}
package "chatbot-be.model.KPIMaster" as chatbot-be.model.KPIMaster {
}
package "chatbot-be.model.KPITracker" as chatbot-be.model.KPITracker {
}
package "chatbot-be.model.PasswordReset" as chatbot-be.model.PasswordReset {
}
package "chatbot-be.model.RevokedToken" as chatbot-be.model.RevokedToken {
}
package "chatbot-be.model.SchedulerConfig" as chatbot-be.model.SchedulerConfig {
}
package "chatbot-be.model.User" as chatbot-be.model.User {
}
package "chatbot-be.repository" as chatbot-be.repository {
}
package "chatbot-be.repository.chatbotRepository" as chatbot-be.repository.chatbotRepository {
}
package "chatbot-be.repository.ingestionLogRepository" as chatbot-be.repository.ingestionLogRepository {
}
package "chatbot-be.repository.kpiGroupRepository" as chatbot-be.repository.kpiGroupRepository {
}
package "chatbot-be.repository.kpiMasterRepository" as chatbot-be.repository.kpiMasterRepository {
}
package "chatbot-be.repository.kpiTrackerRepository" as chatbot-be.repository.kpiTrackerRepository {
}
package "chatbot-be.repository.schedulerRepository" as chatbot-be.repository.schedulerRepository {
}
package "chatbot-be.repository.userRepository" as chatbot-be.repository.userRepository {
}
package "chatbot-be.router" as chatbot-be.router {
}
package "chatbot-be.router.chatbotRouter" as chatbot-be.router.chatbotRouter {
}
package "chatbot-be.router.kpiGroupRouter" as chatbot-be.router.kpiGroupRouter {
}
package "chatbot-be.router.kpiMasterRouter" as chatbot-be.router.kpiMasterRouter {
}
package "chatbot-be.router.kpiTrackerRouter" as chatbot-be.router.kpiTrackerRouter {
}
package "chatbot-be.router.schedulerRouter" as chatbot-be.router.schedulerRouter {
}
package "chatbot-be.router.userRouter" as chatbot-be.router.userRouter {
}
package "chatbot-be.schema" as chatbot-be.schema {
}
package "chatbot-be.schema.authSchema" as chatbot-be.schema.authSchema {
}
package "chatbot-be.schema.chatbotSchema" as chatbot-be.schema.chatbotSchema {
}
package "chatbot-be.schema.kpiGroupSchema" as chatbot-be.schema.kpiGroupSchema {
}
package "chatbot-be.schema.kpiMasterSchema" as chatbot-be.schema.kpiMasterSchema {
}
package "chatbot-be.schema.kpiTrackerSchema" as chatbot-be.schema.kpiTrackerSchema {
}
package "chatbot-be.schema.schedulerSchema" as chatbot-be.schema.schedulerSchema {
}
package "chatbot-be.service" as chatbot-be.service {
}
package "chatbot-be.service.TrackeringestionService" as chatbot-be.service.TrackeringestionService {
}
package "chatbot-be.service.authService" as chatbot-be.service.authService {
}
package "chatbot-be.service.chatbotService" as chatbot-be.service.chatbotService {
}
package "chatbot-be.service.emailService" as chatbot-be.service.emailService {
}
package "chatbot-be.service.googleSheetService" as chatbot-be.service.googleSheetService {
}
package "chatbot-be.service.kpiGroupService" as chatbot-be.service.kpiGroupService {
}
package "chatbot-be.service.kpiMasterIngestionService" as chatbot-be.service.kpiMasterIngestionService {
}
package "chatbot-be.service.kpiMasterService" as chatbot-be.service.kpiMasterService {
}
package "chatbot-be.service.schedulerService" as chatbot-be.service.schedulerService {
}
package "chatbot-be.service.userService" as chatbot-be.service.userService {
}
package "chatbot-be.utils" as chatbot-be.utils {
}
package "chatbot-be.utils.helper" as chatbot-be.utils.helper {
}
package "chatbot-be.utils.kpiMasterParser" as chatbot-be.utils.kpiMasterParser {
}
package "chatbot-be.utils.parser" as chatbot-be.utils.parser {
}
chatbot-be.databaseConfig --> chatbot-be.config
chatbot-be.main --> chatbot-be.databaseConfig
chatbot-be.main --> chatbot-be.middleware.jwtMiddleware
chatbot-be.main --> chatbot-be.model
chatbot-be.main --> chatbot-be.repository.schedulerRepository
chatbot-be.main --> chatbot-be.router
chatbot-be.main --> chatbot-be.router.chatbotRouter
chatbot-be.main --> chatbot-be.router.kpiGroupRouter
chatbot-be.main --> chatbot-be.router.kpiMasterRouter
chatbot-be.main --> chatbot-be.router.kpiTrackerRouter
chatbot-be.main --> chatbot-be.router.schedulerRouter
chatbot-be.main --> chatbot-be.router.userRouter
chatbot-be.main --> chatbot-be.service.schedulerService
chatbot-be.model --> chatbot-be.model.Chatbot
chatbot-be.model --> chatbot-be.model.IngestionLog
chatbot-be.model --> chatbot-be.model.KPIGroup
chatbot-be.model --> chatbot-be.model.KPIMaster
chatbot-be.model --> chatbot-be.model.KPITracker
chatbot-be.model --> chatbot-be.model.SchedulerConfig
chatbot-be.model --> chatbot-be.model.User
@enduml
