"""Remove FK constraints on ingestion_logs kpi_group_id and scheduler_id

Revision ID: 4dba34d05f70
Revises: 918cb24b1586
Create Date: 2026-04-29 14:47:32.166356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dba34d05f70'
down_revision: Union[str, None] = '918cb24b1586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ingestion_logs_scheduler_id_fkey', 'ingestion_logs', type_='foreignkey')
    op.drop_constraint('ingestion_logs_kpi_group_id_fkey', 'ingestion_logs', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('ingestion_logs_kpi_group_id_fkey', 'ingestion_logs', 'kpi_groups', ['kpi_group_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('ingestion_logs_scheduler_id_fkey', 'ingestion_logs', 'scheduler_configs', ['scheduler_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
