"""re_add_source_type_to_ingestion_logs

Revision ID: 7a90fc93f19e
Revises: 160bb0ff01cb
Create Date: 2026-04-29 15:54:59.189854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a90fc93f19e'
down_revision: Union[str, None] = '160bb0ff01cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_logs', sa.Column('source_type', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_ingestion_logs_source_type'), 'ingestion_logs', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_logs_source_type'), table_name='ingestion_logs')
    op.drop_column('ingestion_logs', 'source_type')
    # ### end Alembic commands ###
