"""Change IngestionLog.kpi_group_id to nullable with SET NULL constraint

Revision ID: 918cb24b1586
Revises: b4a1f2c9d8e7
Create Date: 2026-04-29 14:40:26.764097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '918cb24b1586'
down_revision: Union[str, None] = 'b4a1f2c9d8e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS ix_revoked_tokens_token')
    op.execute('DROP TABLE IF EXISTS revoked_tokens')
    op.execute('DROP INDEX IF EXISTS ix_clarification_logs_session_id')
    op.execute('DROP INDEX IF EXISTS ix_clarification_logs_user_id')
    op.execute('DROP TABLE IF EXISTS clarification_logs')
    op.execute('DROP TABLE IF EXISTS tracker_sources')
    op.execute('DROP INDEX IF EXISTS ix_ingestion_source')

    # ▼ FIX ORPHANED DATA: Hapus ingestion logs dengan kpi_group_id yang tidak ada di kpi_groups
    op.execute("""
        DELETE FROM ingestion_logs 
        WHERE kpi_group_id NOT IN (SELECT id FROM kpi_groups)
    """)

    # ▼ Sekarang baru apply constraint dengan SET NULL
    op.execute(
        'CREATE INDEX IF NOT EXISTS ix_ingestion_logs_kpi_group_id ON ingestion_logs (kpi_group_id)')
    op.alter_column('ingestion_logs', 'kpi_group_id',
                    existing_type=postgresql.UUID(as_uuid=True), nullable=True)
    op.execute(
        'ALTER TABLE ingestion_logs DROP CONSTRAINT IF EXISTS ingestion_logs_kpi_group_id_fkey')
    op.execute(
        'ALTER TABLE ingestion_logs ADD CONSTRAINT ingestion_logs_kpi_group_id_fkey FOREIGN KEY (kpi_group_id) REFERENCES kpi_groups(id) ON DELETE SET NULL')
    op.execute('ALTER TABLE ingestion_logs DROP COLUMN IF EXISTS sheet_url')
    op.execute('ALTER TABLE ingestion_logs DROP COLUMN IF EXISTS source_id')
    op.execute('ALTER TABLE ingestion_logs DROP COLUMN IF EXISTS sheet_name')
    op.execute('ALTER TABLE ingestion_logs DROP COLUMN IF EXISTS source_type')
    op.execute('ALTER TABLE ingestion_logs DROP COLUMN IF EXISTS sheet_id')
    op.alter_column('kpi_groups', 'group_type',
                    existing_type=sa.VARCHAR(length=20),
                    type_=sa.Enum('MASTER', 'TRACKER',
                                  name='grouptypeenum', native_enum=False),
                    existing_nullable=False)
    op.alter_column('kpi_groups', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    nullable=False,
                    existing_server_default=sa.text('true'))
    op.execute(
        'ALTER TABLE kpi_tracker_records DROP COLUMN IF EXISTS document_text')
    op.execute('ALTER TABLE kpi_tracker_records DROP COLUMN IF EXISTS source_row')
    op.execute('ALTER TABLE kpi_tracker_records DROP COLUMN IF EXISTS bulan')
    op.alter_column('scheduler_configs', 'interval_value',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True)
    op.alter_column('users', 'role',
                    existing_type=sa.VARCHAR(length=50),
                    type_=sa.Enum('admin', 'kepala_divisi', 'karyawan',
                                  name='roleenum', native_enum=False),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
                    existing_type=sa.Enum(
                        'admin', 'kepala_divisi', 'karyawan', name='roleenum', native_enum=False),
                    type_=sa.VARCHAR(length=50),
                    existing_nullable=False)
    op.alter_column('scheduler_configs', 'interval_value',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False)
    op.add_column('kpi_tracker_records', sa.Column(
        'bulan', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('kpi_tracker_records', sa.Column(
        'source_row', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('kpi_tracker_records', sa.Column(
        'document_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('kpi_groups', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    nullable=True,
                    existing_server_default=sa.text('true'))
    op.alter_column('kpi_groups', 'group_type',
                    existing_type=sa.Enum(
                        'MASTER', 'TRACKER', name='grouptypeenum', native_enum=False),
                    type_=sa.VARCHAR(length=20),
                    existing_nullable=False)
    op.add_column('ingestion_logs', sa.Column('sheet_id', sa.VARCHAR(
        length=255), autoincrement=False, nullable=True))
    op.add_column('ingestion_logs', sa.Column(
        'source_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('ingestion_logs', sa.Column('sheet_name', sa.VARCHAR(
        length=255), autoincrement=False, nullable=True))
    op.add_column('ingestion_logs', sa.Column(
        'source_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('ingestion_logs', sa.Column(
        'sheet_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ingestion_logs', type_='foreignkey')
    op.drop_index(op.f('ix_ingestion_logs_kpi_group_id'),
                  table_name='ingestion_logs')
    op.create_index('ix_ingestion_source', 'ingestion_logs', [
                    'source_type', 'source_id'], unique=False)
    op.create_table('tracker_sources',
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=255),
                              autoincrement=False, nullable=False),
                    sa.Column('sheet_url', sa.TEXT(),
                              autoincrement=False, nullable=False),
                    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text(
                        'true'), autoincrement=False, nullable=False),
                    sa.Column('is_scheduled', sa.BOOLEAN(), server_default=sa.text(
                        'true'), autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(
                        'now()'), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(
                        'now()'), autoincrement=False, nullable=False),
                    sa.Column('tahun', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='tracker_sources_pkey')
                    )
    op.create_table('clarification_logs',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('session_id', sa.VARCHAR(length=255),
                              autoincrement=False, nullable=False),
                    sa.Column('user_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('user_role', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.Column('original_query', sa.TEXT(),
                              autoincrement=False, nullable=False),
                    sa.Column('ambiguity_score', sa.NUMERIC(precision=3, scale=2),
                              autoincrement=False, nullable=False),
                    sa.Column('ambiguity_type', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.Column('decision', sa.VARCHAR(length=10),
                              autoincrement=False, nullable=False),
                    sa.Column('decision_source', sa.VARCHAR(length=20),
                              autoincrement=False, nullable=False),
                    sa.Column('clarifying_question', sa.TEXT(),
                              autoincrement=False, nullable=True),
                    sa.Column('clarification_answer', sa.TEXT(),
                              autoincrement=False, nullable=True),
                    sa.Column('disambiguated_query', sa.TEXT(),
                              autoincrement=False, nullable=True),
                    sa.Column('user_feedback', sa.BOOLEAN(),
                              autoincrement=False, nullable=True),
                    sa.Column('needed_correction', sa.BOOLEAN(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(
                        'now()'), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint(
                        'id', name='clarification_logs_pkey')
                    )
    op.create_index('ix_clarification_logs_user_id',
                    'clarification_logs', ['user_id'], unique=False)
    op.create_index('ix_clarification_logs_session_id',
                    'clarification_logs', ['session_id'], unique=False)
    op.create_table('revoked_tokens',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('token', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('revoked_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='revoked_tokens_pkey')
                    )
    op.create_index('ix_revoked_tokens_token',
                    'revoked_tokens', ['token'], unique=True)
    # ### end Alembic commands ###
