"""Remove scheduler_id column from ingestion_logs

Revision ID: b2aa6e938fec
Revises: c5e3b37b1602
Create Date: 2026-04-29 14:58:30.341508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2aa6e938fec'
down_revision: Union[str, None] = 'c5e3b37b1602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingestion_scheduler_status', table_name='ingestion_logs')
    op.drop_column('ingestion_logs', 'scheduler_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_logs', sa.Column('scheduler_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index('ix_ingestion_scheduler_status', 'ingestion_logs', ['scheduler_id', 'status'], unique=False)
    # ### end Alembic commands ###
