"""drop_ambigous_phrase_column

Revision ID: c3a71be44b6d
Revises: f6a7b8c9d0e1
Create Date: 2026-05-23 11:36:05.902413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3a71be44b6d'
down_revision: Union[str, None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE clarification_questions DROP COLUMN IF EXISTS ambiguous_phrase")
    op.execute("ALTER TABLE kpi_master_records DROP COLUMN IF EXISTS responsibility_persons")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi_master_records', sa.Column('responsibility_persons', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('clarification_questions', sa.Column('ambiguous_phrase', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
