"""Remove relationship back_populates from SchedulerConfig

Revision ID: c5e3b37b1602
Revises: 4dba34d05f70
Create Date: 2026-04-29 14:49:34.102867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5e3b37b1602'
down_revision: Union[str, None] = '4dba34d05f70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
