"""add_group_name_to_ingestion_logs

Revision ID: dd92dd2b0ccf
Revises: 7a90fc93f19e
Create Date: 2026-04-29 16:13:41.728903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd92dd2b0ccf'
down_revision: Union[str, None] = '7a90fc93f19e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_logs', sa.Column('group_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_logs', 'group_name')
    # ### end Alembic commands ###
