"""init

Revision ID: f9c96abf52bc
Revises: 
Create Date: 2026-04-24 21:02:44.073891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c96abf52bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama_chatbot', sa.String(length=255), nullable=False),
    sa.Column('otoritas', sa.Enum('HRD', 'KARYAWAN', name='authorityenum'), nullable=False),
    sa.Column('addon_prompt', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbots_id'), 'chatbots', ['id'], unique=False)
    op.create_index(op.f('ix_chatbots_nama_chatbot'), 'chatbots', ['nama_chatbot'], unique=False)
    op.create_table('kpi_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama_grup', sa.String(length=255), nullable=False),
    sa.Column('group_type', sa.Enum('MASTER', 'TRACKER', name='grouptypeenum', native_enum=False), nullable=False),
    sa.Column('sheet_url', sa.Text(), nullable=False),
    sa.Column('sheet_id', sa.String(length=255), nullable=True),
    sa.Column('sheet_name', sa.String(length=255), nullable=True),
    sa.Column('tahun', sa.Integer(), nullable=True),
    sa.Column('is_scheduled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sheet_id', 'group_type', name='uq_kpigroup_sheet_type')
    )
    op.create_table('scheduler_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interval_value', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'hrd', 'kepala_divisi', 'karyawan', name='roleenum', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('chatbot_audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_role', sa.String(length=20), nullable=True),
    sa.Column('user_query', sa.Text(), nullable=True),
    sa.Column('generated_sql', sa.Text(), nullable=True),
    sa.Column('wireguard_status', sa.String(length=10), nullable=True),
    sa.Column('wireguard_reason', sa.Text(), nullable=True),
    sa.Column('execution_status', sa.String(length=20), nullable=True),
    sa.Column('rows_returned', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_audit_log_session_id'), 'chatbot_audit_log', ['session_id'], unique=False)
    op.create_index(op.f('ix_chatbot_audit_log_user_id'), 'chatbot_audit_log', ['user_id'], unique=False)
    op.create_table('ingestion_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kpi_group_id', sa.UUID(), nullable=False),
    sa.Column('scheduler_id', sa.UUID(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('ingested_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('success', 'failed')", name='ck_ingestion_status'),
    sa.ForeignKeyConstraint(['kpi_group_id'], ['kpi_groups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scheduler_id'], ['scheduler_configs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_created_brin', 'ingestion_logs', ['created_at'], unique=False, postgresql_using='brin')
    op.create_index('ix_ingestion_kpi_group', 'ingestion_logs', ['kpi_group_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ingestion_logs_kpi_group_id'), 'ingestion_logs', ['kpi_group_id'], unique=False)
    op.create_index('ix_ingestion_scheduler_status', 'ingestion_logs', ['scheduler_id', 'status'], unique=False)
    op.create_table('kpi_master_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('tahun', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('kpi_name', sa.String(length=255), nullable=False),
    sa.Column('definisi_operasional', sa.Text(), nullable=True),
    sa.Column('target', sa.String(length=100), nullable=True),
    sa.Column('achieve', sa.String(length=100), nullable=True),
    sa.Column('partial', sa.String(length=100), nullable=True),
    sa.Column('fail', sa.String(length=100), nullable=True),
    sa.Column('responsibility_persons', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['kpi_groups.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'kpi_name', name='uq_kpimaster_group_name')
    )
    op.create_index('ix_kpimaster_group_category', 'kpi_master_records', ['group_id', 'category'], unique=False)
    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_resets_user_id'), 'password_resets', ['user_id'], unique=False)
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_tokens_token'), 'revoked_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_revoked_tokens_user_id'), 'revoked_tokens', ['user_id'], unique=False)
    op.create_table('kpi_tracker_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('kpi_master_id', sa.UUID(), nullable=True),
    sa.Column('tahun', sa.Integer(), nullable=False),
    sa.Column('bulan_num', sa.Integer(), nullable=True),
    sa.Column('realisasi', sa.String(length=100), nullable=True),
    sa.Column('nama_orang', sa.String(length=255), nullable=True),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('document_text', sa.Text(), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['kpi_groups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['kpi_master_id'], ['kpi_master_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kpitracker_created_brin', 'kpi_tracker_records', ['created_at'], unique=False, postgresql_using='brin')
    op.create_index('ix_kpitracker_group_orang', 'kpi_tracker_records', ['group_id', 'nama_orang'], unique=False)
    op.create_index('ix_kpitracker_master_orang', 'kpi_tracker_records', ['kpi_master_id', 'nama_orang'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_kpitracker_master_orang', table_name='kpi_tracker_records')
    op.drop_index('ix_kpitracker_group_orang', table_name='kpi_tracker_records')
    op.drop_index('ix_kpitracker_created_brin', table_name='kpi_tracker_records', postgresql_using='brin')
    op.drop_table('kpi_tracker_records')
    op.drop_index(op.f('ix_revoked_tokens_user_id'), table_name='revoked_tokens')
    op.drop_index(op.f('ix_revoked_tokens_token'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_index(op.f('ix_password_resets_user_id'), table_name='password_resets')
    op.drop_table('password_resets')
    op.drop_index('ix_kpimaster_group_category', table_name='kpi_master_records')
    op.drop_table('kpi_master_records')
    op.drop_index('ix_ingestion_scheduler_status', table_name='ingestion_logs')
    op.drop_index(op.f('ix_ingestion_logs_kpi_group_id'), table_name='ingestion_logs')
    op.drop_index('ix_ingestion_kpi_group', table_name='ingestion_logs')
    op.drop_index('ix_ingestion_created_brin', table_name='ingestion_logs', postgresql_using='brin')
    op.drop_table('ingestion_logs')
    op.drop_index(op.f('ix_chatbot_audit_log_user_id'), table_name='chatbot_audit_log')
    op.drop_index(op.f('ix_chatbot_audit_log_session_id'), table_name='chatbot_audit_log')
    op.drop_table('chatbot_audit_log')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('scheduler_configs')
    op.drop_table('kpi_groups')
    op.drop_index(op.f('ix_chatbots_nama_chatbot'), table_name='chatbots')
    op.drop_index(op.f('ix_chatbots_id'), table_name='chatbots')
    op.drop_table('chatbots')
    # ### end Alembic commands ###
